name: Back
on:
  # pull_request:
  push:
    branches:
      - main
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: BackServer Settings
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          cd back
          echo "${ENV_FILE}" > .env
      - name: Upload BackServer build floder to EC2 instance
        env:
          BACK_PEM_FILE: ${{ secrets.BACK_PEM }}
          EC2_USER: ${{ secrets.BACK_USER }}
          EC2_HOST: ${{ secrets.BACK_HOST }}
        run: |
          echo "${BACK_PEM_FILE}" > exfrserver.pem
          ls
          chmod 600 exfrserver.pem
          chmod 400 exfrserver.pem
          mkdir -p ~/.ssh 
          ssh-keyscan -t rsa ${EC2_HOST} >> ~/.ssh/known_hosts
          scp -i exfrserver.pem -r ./back ${EC2_USER}@${EC2_HOST}:/home/ubuntu/www
